### ISSUE TITLE
In continuation of my recently closed issue no #13 on running of 'trafo'

### ISSUE THREAD

**Issue by snborah** [spex-xray/spex-help#14]
In reference to above mentioned issue no #13 and your suggestion, I am facing another problem. I used new bin boundary value as '3E-5' (as you mentioned), the programme runned for more than 1 hour , without any response, and I have to forced stop. I checked it for three different xmm observations and found the same situation. File could not be converted in to SPEX readable formate.
As in terminal:
" No response matrix file specified in pha-file.
 Enter filename response matrix to be read: M1_rmf.rmf
 Reading response matrix ...
 Lower model bin boundary for bin        1 must be positive; current values:   0.000000E+00  5.000000E-03
 Enter new bin boundary values manually: 3E-5    "    

Please suggest me what is the problem. I am using a HP core i7 laptop running FC 29. 
Regards,

SN Borah

**Comment by jdeplaa** [comment]
Sorry, I think you need to specify both the lower bin boundary and the upper bin boundary on that line, so:

`Enter new bin boundary values manually: 3E-5 5E-3`

With the entry above, it should continue creating the matrix.

**Comment by snborah** [comment]
Yes, it is working. Thanks for suggestion. File converted into SPEX format.
Thanks  and regards.
