### ISSUE TITLE
Website files offline

### ISSUE THREAD

**Issue by EfremBraun** [spex-xray/spex-help#16]
I'm not able to access any of the files shown on https://www.sron.nl/astrophysics-spex/physics (e.g., the lines lists). I get a "This site can't be reached" error.

**Comment by jdeplaa** [comment]
Thank you very much for reporting this! Our institute is moving to a new location, including most ICT facilities. The links to these files must have been broken in the moving process. We will move them to an accessible location. I will report back when it is done.

**Comment by jdeplaa** [comment]
The files on this page should now be accessible again. Thanks a lot for reporting.
