### ISSUE TITLE
spexdist.sh ulimit setting

### ISSUE THREAD

**Issue by jmao2014** [spex-xray/spex-help#20]
Hi Jelle, 

My student noticed an issue when installing SPEX on macOS (via admin). When sourcing spexdish.sh, the following error occurs: 

./spexdist.sh: line 21: ulimit: stack size: cannot modify limit: Operation not permitted

The root of the issue is the last line in spexdist.sh: "ulimit -s 65532". A smaller value is acceptable (32767 for my student). This value can be obtained via the command "ulimit -a", which returns a stack size of 32767 kbytes. 

Cheers,

Junjie

**Comment by jdeplaa** [comment]
Hi Junjie,

Thanks for reporting this! On Mac, the scripts should have been created with the line:

`ulimit -s 65532`

This is how our CMake setup should create them, but apparently it is different in the DMG file that your student downloaded. Which version of SPEX did you download?

Cheers,

Jelle.

**Comment by jmao2014** [comment]
Hi Jelle, 

I will ask my student tomorrow to provide details then. His macOS is Big Sur (I don't recall the detailed version number). It should be the latest version of SPEX that he was trying to install. 

Mine is currently Monterey (12.2.1, but old CPU chips) and it works fine with "ulimits -s 65532". 

Cheers,

Junjie

**Comment by jdeplaa** [comment]
Dear Taishu,

Thank you very much for this information! I will try to solve this issue for the next release of SPEX.

Cheers,

Jelle.

**Comment by jdeplaa** [comment]
This problem has been fixed in the latest SPEX releases. For Mac, the command `ulimit -s hard` appears to set the stacksize to the limit of the OS.
