### ISSUE TITLE
pyspex and jupyter notebook

### ISSUE THREAD

**Issue by ipsarad** [spex-xray/spex-help#24]
Hi Jelle,

I attempt to use pyspex via a jupyter notebook. I can normally call pyspex from the notebook (following this --> [https://github.com/spex-xray/spex-help/issues/6]), but my kernel is dying as soon as I receive the 'Welcome to SPEX' message in my terminal. Have you by any chance had this issue before?
I am using chrome and an M1 chip mac - although I don't know if this is relevant. 

Thank you!
Cheers,
Ioanna

**Comment by jdeplaa** [comment]
Hi Ioanna,

Thanks for reporting this! I do not think that I have seen this issue before. Do you get any more information about the kernel dying? If not, you could also try to run the jupyter kernel from the terminal command line like this using ipython:

```
(spex) ioanna@mac ~ %   ipython console --kernel spex
In [1]: from pyspex.spex import Session
In [2]: s=Session()
```
Do you get any errors when you execute these commands in a terminal? If yes, could you copy/paste them to this issue?

**Comment by ipsarad** [comment]
Hi Jelle,

I can execute these commands normally on my terminal. Upgrading the numpy version solved this issue.

Cheers,
Ioanna
