### ISSUE TITLE
SPEX demo spectra link ~broken

### ISSUE THREAD

**Issue by rjfarber** [spex-xray/spex-help#26]
While https://github.com/spex-xray/spex-help/blob/master/source/getstarted/runspex.rst does have a valid link to https://www.sron.nl/astrophysics-spex/manual, the "examples" and "exercises" links are broken.

**Comment by jdeplaa** [comment]
Thanks a lot for reporting! The link to the files was indeed broken and it has been solved. You can find example SPEX fits files in the 'Exercises' section. The manual text is fixed in commit 51f7c232722de7f923679bc04ad9cb091bd1ad43.
