### ISSUE TITLE
Python module CMake error with Python 3.11/Fedora 38

### ISSUE THREAD

**Issue by wilkinsdr** [spex-xray/spex-help#28]
There is an issue with the CMake configuration for the SPEX Python module (in the source distribution), causing CMake (or compile.py) to fail when the python module is enabled.

In cmake/FindPythonExtensions.cmake, line 284, sysconfig.get_config_var('SO') returns NoneType on Python 3.11 (on Fedora 38), so should be changed to sysconfig.get_config_var('SHLIB_SUFFIX')

**Comment by jdeplaa** [comment]
Dear Dan, Thanks a lot for reporting this and for providing the solution. I did not test the Fedora / Python 3.11 combination yet. The line will be fixed in the next SPEX version.
