### ISSUE TITLE
ascdump set commands not working

### ISSUE THREAD

**Issue by jzuhone** [spex-xray/spex-help#35]
Hello, 

I installed SPEX 3.07.03 using the pkg installer for macOS (also tried the anaconda installer), but in both cases I get the following error when attempting to use any `ascdump set` command: 

```
SPEX> ascdump set flux 0
Your command cannot be interpreted. Check the appropriate syntax
```

**Comment by jdeplaa** [comment]
Dear John,

Thanks for asking this question! The syntax of the `ascdump` command changed in version 3.07.00. The way that you can select ascdump output in the command-line interface is described here:

https://spex-xray.github.io/spex-help/reference/commands/ascdump.html#selection-sorting-and-formatting-of-the-data

I saw that some parts of the command-line documentation were not updated properly. We will update this in the next SPEX version. 

Let me know if anything is still unclear.

**Comment by jdeplaa** [comment]
Yes. In the selection file you can provide a flux range that you want to filter the output with. Add the following line in the selection file:
```
sel flux 1E+20 1E+35
```
