### ISSUE TITLE
[PYSPEX] Error with plot_comp()

### ISSUE THREAD

**Issue by Laamkh** [spex-xray/spex-help#40]
Hi, I have been attempting to calculate some theoretical spectra from models and would like to plot the individual additive components. However, I encountered an error message that said 'You cannot plot this frame since nothing is defined'. It works fine with plot_model(). Could you please help me understand what went wrong and suggest a possible solution? I am a new user of PYSPEX and have only used SPEX for a while. I hope you don't mind if this is a stupid question. 

Thank you!

Here is the section of my code for your reference:
```
s=spex.Session()
s.command('var calc new')

s.com('cie')
s.com('cx')

s.dist(1,3,'mpc')
s.dist_get(1)

s.calc()

s.par_show()

s.plot_model()
s.plot_comp()

z = input()

plt.close()

```

and here is the terminal output
```
Number of additive components: 2
Calculate component 1 1...
 You cannot plot this frame since nothing is defined
 
Calculate component 1 2...
 You cannot plot this frame since nothing is defined
 
Traceback (most recent call last):
  File "/cluster/home/whllee/code_GF_1.0/test/spex/x_ray_cloud.py", line 91, in <module>
    s.plot_comp()
  File "/cluster/home/whllee/.conda/envs/spex/opt/spex/python/pyspex/spex.py", line 1322, in plot_comp
    pl.plot_comp(xlog=xlog, ylog=ylog, wave=wave, title=title, show=show)
  File "/cluster/home/whllee/.conda/envs/spex/opt/spex/python/pyspex/plot.py", line 619, in plot_comp
    plt.xlabel('Energy ({0})'.format(self.inst[0].reg[0].tabdata['X_ctr'].unit.to_string('latex_inline')))
IndexError: list index out of range
 Thank you for using SPEX 
```

**Comment by jdeplaa** [comment]
Dear @Laamkh,

Thanks a lot for reporting this error. It looks like the error occurs in the ``plot_comp()`` function. The reason that it fails is because the ``plot_comp`` function assumes that there is some spectral data loaded. Since you are just calculating models,  it fails on the missing spectral data.

If you want to plot the ``cie `` and ``cx`` components separately, you can do that by introducing a new sector. This allows you to create new model 'groups' that can be plotted separately. Please see the example below:

```
from pyspex.spex import Session
s=Session()
s.command('var calc new')

s.com('cie')

# Here we create a new sector
s.sector()

# Now let's put the cx component in sector 2
s.com('cx', isect=2)

# Below, I do a bit more advanced stuff to get the data from the plot command.
# This allows me to give the two model sectors different colors in the plot.
import matplotlib.pyplot as plt

# The command below gets the plot data saved to the pldata variable
(pldata, plt) = s.plot_model(show=False)

# Now we plot the energy column and model spectrum of each sector.
# Please note that python calculates from 0, so the sector index is the sector number -1:
plt.plot(pldata.sector[0].tabmodel['X_ctr'], pldata.sector[0].tabmodel['Model'], '-r', label='CIE')
plt.plot(pldata.sector[1].tabmodel['X_ctr'], pldata.sector[1].tabmodel['Model'], '-b', label='CX')

# Make it a log-log plot
plt.xscale('log')
plt.yscale('log')

# Add a legend for clarity
plt.legend()

# And show the plot
plt.show()
```

The above should yield this plot:
![CIE_CX](https://github.com/spex-xray/spex-help/assets/27801798/e72e597d-c0cb-4dcd-9bd3-df47bd30f586)

I hope this answers your question.

**Comment by Laamkh** [comment]
Thanks a lot! The example works very well for me.

**Comment by Laamkh** [comment]
@jdeplaa Thanks a lot! The example works very well for me.
