### ISSUE TITLE
How do we use three additive components simultaneously when using the “comp rel” command?

### ISSUE THREAD

**Issue by TaoWu666** [spex-xray/spex-help#41]
Hi Jelle,

I have had a problem recently. I want to add 3 additive components simultaneously with the "comp rel" command, such as "comp rel 1:2:3 5,6,4". But this was told that it was not allowed. 

Cheers,

Tao.

**Comment by jdeplaa** [comment]
Hi Tao,

Given your example, you can provide a range of additive components in SPEX. You can write the command like this:
```
comp rel 1:3 5,6,4
```
The ':' is an indicator in the SPEX syntax that the two numbers given are a range, so 1:2:3 does not work. The syntax `1:3` implicitly means 1, 2 and 3.

You can also have a case where the additive components are not loaded in sequence. In that case, you can give multiple `comp rel` commands:
```
com rel 1 2
com rel 3 2,4
```
where component 1 and 3 are additive, and 2 and 4 multiplicative. So here you define the relations for each additive component individually.

Cheers,

Jelle.

**Comment by TaoWu666** [comment]
Hi Jelle,

I have got it. Thank you for your help!

Cheers,

Tao.
